---

galaxy_info:
  author: foosinn
  description: Ansible role to setup Engelsystem.
  license: Apache-2.0
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10

  galaxy_tags:
    - engelsystem

dependencies: []
